### ISSUE TITLE
m3u, xml 파일 위치

### ISSUE THREAD

**Issue by taxdriver4u** [wiserain/docker-klive-server#1]
KLive 서버를 터미널로 직접설치한 경우,

output폴더에 klive_ custom.m3u와 klive_custom.xml이 생성되는 것을 확인할 수 있습니다.

m3u, xml파일을 kodi나 TVirl에서 사용하고자 하는데

도커로 설치한 경우, 위 m3u, xml파일을 어디서 확인할 수 있는지요?

**Comment by wiserain** [comment]
제가 이걸 몰랐네요. 저도 쓰는 것만 쓰다보니 output 폴더에 epg랑 m3u가 제공되는지 몰랐습니다. 그런데 소스를 확인해보면 output 폴더의 모든 내용물이 웹으로 제공되고 있습니다. ```/m3u``` ```/m3uall``` ```/epg```로 접속하면 내용물을 받아볼 수 있습니다.

정 로컬에서 파일 내용을 확인하고 싶으시다면 볼륨 매핑을 하나 더 해주시면 됩니다. 예를 들면 ```-v ${LOCAL_FOLDER}/klve/output:/klive_server/output```

**Comment by taxdriver4u** [comment]
답변 감사드립니다.

TVirl의 경우 '~/epg' url을 입력해도 epg가 입혀지지 않고 xml형식만 적용가능한 이유로 질문드리게 되었습니다.

**Comment by taxdriver4u** [comment]
![image](https://user-images.githubusercontent.com/44728502/52467049-7dc41700-2bc7-11e9-8439-ec4054c8c8eb.png)

**Comment by wiserain** [comment]
네 제가 해당 앱을 쓰지 않아서 잘 모르겠습니다만 파일은 위에 말씀드린 방법으로 접근하실 수 있습니다.
